### ISSUE TITLE
Rupee sign in fundslist page

### ISSUE THREAD

**Issue by rishikeshsreehari** [rishikeshsreehari/npsnav#14]
https://npsnav.in/nps-funds-list

**Comment by rishikeshsreehari** [comment]
@sd416 Is this because the funds-table has the following CSS:

table tr td:nth-child(2)::before {
    content: '₹';
  }
  
 So the second column shows the rupee sign as the class is same for both tables?

**Comment by sd416** [comment]
Ah yes, I think need to have different class for the these two tables, did not think about this.
